# Generated by Django 3.2.9 on 2021-11-03 21:33

from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[msgserver.models.validate_key_range]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=160, validators=[msgserver.models.validate_message_range]),
        ),
    ]
